export default {
  COLOR_BOX_SHADOW: "rgba(115, 115, 115, 0.3)",

  COLOR_NAV_TEXT: "#7D7D7D",

  COLOR_FOOTER_BACKGROUND: "#5B5B5B",

  COLOR_LIGHTGRAY_TEXT: "#D0D0D0",

  COLOR_GRAY_BORDER: "#D1D1D1",

  COLOR_MINT_BACKGROUND: "#B2DFDF",

  COLOR_YELLOW_BACKGROUND: "#FFD748",

  COLOR_LAVENDAR_BACKGROUND: "#DDDAF2",

  COLOR_GRAY_BACKGROUND: "#E5E5E5",

  COLOR_BLUE_TEXT: "#557FEB",
  COLOR_GRAY_TEXT: "#6C6C6C",
};
